services:

  web:
      build: .
      command: bundle exec rails s -b 0.0.0.0 -p 3000
      volumes:
        - .:/app
      ports:
        - 3000:3000
      depends_on:
        - postgres

  postgres:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    env_file: .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} -h postgres
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  postgres_data: {}
